title: Squoteboarder
default_lang: en
author:
  name: 'Jordan Louapre'
  email: jordan.louapre@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Place where skateboarders quote'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
