title: theSQUOTEBOARDER
default_lang: en
author:
  name: 'Jordan LOUAPRE'
  email: jordan.louapre@gmail.com
taxonomies:
  - post_type
  - category
  - tag
  - author
  - source_media
metadata:
  description: 'Quoting is not a crime.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
navigation_secondary:
-
  url: /about
  menu: About
-
  url: /contact
  menu: Contact
navigation_footer:
-
  url: /terms-of-use
  menu: Terms of use
-
  url: /privacy-policy
  menu: Privacy policy
-
  url: /cookie-policy
  menu: Cookie policy
skateboarders:
  ekoston: Koston|Eric|froston
  sberra: Berra|Steve|sberra
images_dir: user/pages/images
source_medias:
  thrashermagazine: 'Thrasher Magazine|https://www.thrashermagazine.com/'
