title: theSQUOTEBOARDER
default_lang: en
author:
  name: 'Jordan LOUAPRE'
  email: jordan.louapre@gmail.com
taxonomies:
  - post_type
  - category
  - tag
  - author
  - source_media
metadata:
  description: 'Quoting is not a crime.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
skateboarders:
  ekoston: Koston|Eric|froston
  sberra: Berra|Steve|sberra
images_dir: user/pages/images
source_medias:
  thrashermagazine: 'Thrasher Magazine|https://www.thrashermagazine.com/'
